import { ReplayData, GameEvent, GoldSnapshot, Player } from "@/types/replay";

const bluePlayers: Player[] = [
  {
    summonerName: "TopDiff420",
    championName: "Darius",
    championId: 122,
    team: "blue",
    role: "TOP",
    kills: 5,
    deaths: 3,
    assists: 7,
    cs: 198,
    csPerMin: 6.6,
    gold: 12400,
    goldPerMin: 413,
    damageDealt: 142000,
    damageToChampions: 18500,
    damageTaken: 28000,
    visionScore: 22,
    wardsPlaced: 8,
    wardsKilled: 2,
    level: 16,
    items: [3078, 3053, 3047, 3742, 3065, 3364],
    spells: ["Flash", "Teleport"],
    runes: { primary: "Conqueror", secondary: "Resolve" },
  },
  {
    summonerName: "JGKing99",
    championName: "Lee Sin",
    championId: 64,
    team: "blue",
    role: "JUNGLE",
    kills: 8,
    deaths: 4,
    assists: 12,
    cs: 156,
    csPerMin: 5.2,
    gold: 13200,
    goldPerMin: 440,
    damageDealt: 98000,
    damageToChampions: 15200,
    damageTaken: 22000,
    visionScore: 38,
    wardsPlaced: 14,
    wardsKilled: 6,
    level: 15,
    items: [6692, 3071, 3047, 3026, 3156, 3364],
    spells: ["Flash", "Smite"],
    runes: { primary: "Conqueror", secondary: "Inspiration" },
  },
  {
    summonerName: "xMidGapx",
    championName: "Ahri",
    championId: 103,
    team: "blue",
    role: "MID",
    kills: 11,
    deaths: 2,
    assists: 9,
    cs: 224,
    csPerMin: 7.5,
    gold: 15800,
    goldPerMin: 527,
    damageDealt: 168000,
    damageToChampions: 24300,
    damageTaken: 14000,
    visionScore: 28,
    wardsPlaced: 10,
    wardsKilled: 3,
    level: 17,
    items: [6655, 3089, 3135, 3157, 3020, 3364],
    spells: ["Flash", "Ignite"],
    runes: { primary: "Electrocute", secondary: "Inspiration" },
  },
  {
    summonerName: "ADCarry1v9",
    championName: "Jinx",
    championId: 222,
    team: "blue",
    role: "ADC",
    kills: 9,
    deaths: 5,
    assists: 8,
    cs: 242,
    csPerMin: 8.1,
    gold: 15200,
    goldPerMin: 507,
    damageDealt: 195000,
    damageToChampions: 28900,
    damageTaken: 16500,
    visionScore: 18,
    wardsPlaced: 7,
    wardsKilled: 1,
    level: 16,
    items: [3031, 3094, 3085, 6676, 3006, 3364],
    spells: ["Flash", "Heal"],
    runes: { primary: "Lethal Tempo", secondary: "Inspiration" },
  },
  {
    summonerName: "WardBot3000",
    championName: "Thresh",
    championId: 412,
    team: "blue",
    role: "SUPPORT",
    kills: 2,
    deaths: 6,
    assists: 22,
    cs: 34,
    csPerMin: 1.1,
    gold: 8900,
    goldPerMin: 297,
    damageDealt: 24000,
    damageToChampions: 6800,
    damageTaken: 18000,
    visionScore: 62,
    wardsPlaced: 28,
    wardsKilled: 12,
    level: 13,
    items: [3190, 3109, 3047, 2065, 3364, 0],
    spells: ["Flash", "Ignite"],
    runes: { primary: "Aftershock", secondary: "Inspiration" },
  },
];

const redPlayers: Player[] = [
  {
    summonerName: "RivenOnlyOTP",
    championName: "Riven",
    championId: 92,
    team: "red",
    role: "TOP",
    kills: 4,
    deaths: 4,
    assists: 5,
    cs: 210,
    csPerMin: 7.0,
    gold: 11800,
    goldPerMin: 393,
    damageDealt: 135000,
    damageToChampions: 16200,
    damageTaken: 24000,
    visionScore: 15,
    wardsPlaced: 6,
    wardsKilled: 1,
    level: 16,
    items: [6692, 3071, 3156, 3047, 3026, 3364],
    spells: ["Flash", "Ignite"],
    runes: { primary: "Conqueror", secondary: "Inspiration" },
  },
  {
    summonerName: "DarkJungler",
    championName: "Viego",
    championId: 234,
    team: "red",
    role: "JUNGLE",
    kills: 6,
    deaths: 7,
    assists: 8,
    cs: 142,
    csPerMin: 4.7,
    gold: 11200,
    goldPerMin: 373,
    damageDealt: 88000,
    damageToChampions: 13500,
    damageTaken: 26000,
    visionScore: 24,
    wardsPlaced: 9,
    wardsKilled: 4,
    level: 14,
    items: [6632, 3153, 3047, 3071, 3364, 0],
    spells: ["Flash", "Smite"],
    runes: { primary: "Conqueror", secondary: "Domination" },
  },
  {
    summonerName: "YasuoPowerspike",
    championName: "Yasuo",
    championId: 157,
    team: "red",
    role: "MID",
    kills: 7,
    deaths: 8,
    assists: 4,
    cs: 186,
    csPerMin: 6.2,
    gold: 12000,
    goldPerMin: 400,
    damageDealt: 152000,
    damageToChampions: 19800,
    damageTaken: 22000,
    visionScore: 12,
    wardsPlaced: 5,
    wardsKilled: 0,
    level: 15,
    items: [3031, 3153, 3006, 3046, 3156, 3364],
    spells: ["Flash", "Ignite"],
    runes: { primary: "Lethal Tempo", secondary: "Resolve" },
  },
  {
    summonerName: "Kai$aMoney",
    championName: "Kai'Sa",
    championId: 145,
    team: "red",
    role: "ADC",
    kills: 5,
    deaths: 6,
    assists: 9,
    cs: 218,
    csPerMin: 7.3,
    gold: 13000,
    goldPerMin: 433,
    damageDealt: 172000,
    damageToChampions: 21400,
    damageTaken: 15000,
    visionScore: 16,
    wardsPlaced: 6,
    wardsKilled: 2,
    level: 15,
    items: [3124, 3115, 3020, 3089, 3135, 3364],
    spells: ["Flash", "Heal"],
    runes: { primary: "Hail of Blades", secondary: "Inspiration" },
  },
  {
    summonerName: "LuluGoBrrr",
    championName: "Lulu",
    championId: 117,
    team: "red",
    role: "SUPPORT",
    kills: 1,
    deaths: 10,
    assists: 14,
    cs: 28,
    csPerMin: 0.9,
    gold: 7800,
    goldPerMin: 260,
    damageDealt: 18000,
    damageToChampions: 4200,
    damageTaken: 14000,
    visionScore: 48,
    wardsPlaced: 22,
    wardsKilled: 8,
    level: 12,
    items: [3504, 3107, 3117, 3011, 3364, 0],
    spells: ["Flash", "Exhaust"],
    runes: { primary: "Summon Aery", secondary: "Resolve" },
  },
];

const events: GameEvent[] = [
  { timestamp: 180, type: "KILL", description: "JGKing99 (Lee Sin) ganked top - First Blood on RivenOnlyOTP", position: { x: 25, y: 20 }, participants: ["JGKing99", "TopDiff420", "RivenOnlyOTP"], team: "blue", importance: "high" },
  { timestamp: 240, type: "WARD_PLACED", description: "WardBot3000 placed a control ward at dragon pit", position: { x: 50, y: 65 }, participants: ["WardBot3000"], team: "blue", importance: "low" },
  { timestamp: 305, type: "KILL", description: "xMidGapx (Ahri) solo killed YasuoPowerspike in mid lane", position: { x: 50, y: 50 }, participants: ["xMidGapx", "YasuoPowerspike"], team: "blue", importance: "medium" },
  { timestamp: 360, type: "DRAGON", description: "Blue team secured Infernal Drake", position: { x: 48, y: 68 }, participants: ["JGKing99"], team: "blue", importance: "high" },
  { timestamp: 420, type: "TOWER", description: "Blue team destroyed Red top outer tower", position: { x: 20, y: 15 }, team: "blue", importance: "medium" },
  { timestamp: 480, type: "KILL", description: "DarkJungler (Viego) caught ADCarry1v9 overextended bot", position: { x: 75, y: 80 }, participants: ["DarkJungler", "ADCarry1v9"], team: "red", importance: "medium" },
  { timestamp: 510, type: "DEATH", description: "WardBot3000 (Thresh) died trying to save ADCarry1v9", position: { x: 73, y: 78 }, participants: ["WardBot3000", "Kai$aMoney"], team: "red", importance: "low" },
  { timestamp: 600, type: "RIFT_HERALD", description: "Blue team secured Rift Herald", position: { x: 48, y: 35 }, participants: ["JGKing99"], team: "blue", importance: "medium" },
  { timestamp: 660, type: "TOWER", description: "Blue team used Herald to destroy mid outer tower", position: { x: 50, y: 45 }, team: "blue", importance: "medium" },
  { timestamp: 720, type: "TEAM_FIGHT", description: "3v3 skirmish mid - Blue won (2 for 1)", position: { x: 52, y: 48 }, participants: ["xMidGapx", "JGKing99", "TopDiff420", "YasuoPowerspike", "DarkJungler", "RivenOnlyOTP"], team: "blue", importance: "high" },
  { timestamp: 780, type: "KILL", description: "xMidGapx (Ahri) roamed bot and got a double kill", position: { x: 70, y: 75 }, participants: ["xMidGapx", "Kai$aMoney", "LuluGoBrrr"], team: "blue", importance: "high" },
  { timestamp: 840, type: "DRAGON", description: "Blue team secured Mountain Drake", position: { x: 48, y: 68 }, participants: ["JGKing99"], team: "blue", importance: "high" },
  { timestamp: 900, type: "KILL", description: "RivenOnlyOTP split pushed and killed TopDiff420 1v1", position: { x: 18, y: 12 }, participants: ["RivenOnlyOTP", "TopDiff420"], team: "red", importance: "medium" },
  { timestamp: 960, type: "OBJECTIVE_CONTEST", description: "Red team contested but failed to secure dragon", position: { x: 48, y: 68 }, participants: ["DarkJungler", "JGKing99"], team: "blue", importance: "medium" },
  { timestamp: 1020, type: "TOWER", description: "Red team destroyed Blue bot outer tower", position: { x: 80, y: 85 }, team: "red", importance: "medium" },
  { timestamp: 1080, type: "TEAM_FIGHT", description: "5v5 at dragon - Blue aced Red (5 for 2)", position: { x: 50, y: 65 }, participants: ["xMidGapx", "JGKing99", "ADCarry1v9", "TopDiff420", "WardBot3000"], team: "blue", importance: "critical" },
  { timestamp: 1140, type: "BARON", description: "Blue team secured Baron Nashor after teamfight win", position: { x: 48, y: 35 }, participants: ["JGKing99"], team: "blue", importance: "critical" },
  { timestamp: 1200, type: "TOWER", description: "Blue team destroyed Red mid inner tower with Baron", position: { x: 60, y: 40 }, team: "blue", importance: "medium" },
  { timestamp: 1260, type: "INHIBITOR", description: "Blue team destroyed Red mid inhibitor", position: { x: 68, y: 32 }, team: "blue", importance: "high" },
  { timestamp: 1320, type: "TEAM_FIGHT", description: "Final teamfight at Red base - Blue won decisively", position: { x: 75, y: 25 }, participants: ["xMidGapx", "JGKing99", "ADCarry1v9", "TopDiff420", "WardBot3000"], team: "blue", importance: "critical" },
  { timestamp: 1380, type: "KILL", description: "ADCarry1v9 (Jinx) got a Quadra Kill in the final fight", position: { x: 78, y: 22 }, participants: ["ADCarry1v9"], team: "blue", importance: "critical" },
];

const goldTimeline: GoldSnapshot[] = [];
for (let t = 0; t <= 1800; t += 60) {
  const blueBase = 2500 + t * 7.5 + Math.sin(t / 200) * 800;
  const redBase = 2500 + t * 6.8 + Math.cos(t / 180) * 600;
  goldTimeline.push({
    timestamp: t,
    blueGold: Math.round(blueBase),
    redGold: Math.round(redBase),
  });
}

export const sampleReplay: ReplayData = {
  gameId: "NA1_4892371056",
  gameDuration: 1800,
  gameVersion: "14.8.1",
  mapId: 11,
  queueType: "Ranked Solo/Duo",
  winner: "blue",
  players: [...bluePlayers, ...redPlayers],
  events,
  goldTimeline,
  focusedPlayer: "ADCarry1v9",
};
